version: '2'
services:
  cloud-demo:
    image: reg1.sgeg.shenhua.cc/devops/demo/eccl/cloud-demo
    container_name: cloud
    restart: always
    networks:
      - eureka-net
      - db-net
    ports:
      - "80:8803"
    environment:
      TZ: Asia/Shanghai
      spring.datasource.url: jdbc:mysql://db:3306/demo?useUnicode=true&characterEncoding=UTF-8
      spring.datasource.username: demo
      spring.datasource.password: demo2019
      spring.liquibase.enabled: "true"
      eureka.client.serviceUrl.defaultZone: http://eureka-server1:8500/eureka/, http://eureka-server2:8500/eureka/
      eureka.client.fetchRegistry: "true"
      eureka.client.registerWithEureka: "true"
      logging.level.org.springframework: error
      logging.level.org.liquibase: error
      logging.level.liquibase: error



    depends_on:
      - "db"
      - "eureka-server1"
      - "eureka-server2"


  eureka-server1:
    image: reg1.sgeg.shenhua.cc/devops/demo/eccl/eureka-server
    container_name: eureka-server1
    hostname: eureka-server1
    networks:
      - eureka-net
    ports:
      - 8001:8500
    environment:
      spring.profiles.active: eureka-server1
      spring.application.name: eureka-server1
      eureka.client.serviceUrl.defaultZone: http://eureka-server2:8500/eureka/
      eureka.client.fetchRegistry: "true"
      eureka.client.register-with-eureka: "true"

  eureka-server2:
    image: reg1.sgeg.shenhua.cc/devops/demo/eccl/eureka-server
    container_name: eureka-server2
    hostname: eureka-server2
    networks:
      - eureka-net
    ports:
      - 8002:8500
    environment:
      spring.profiles.active: eureka-server2
      spring.application.name: eureka-server2
      eureka.client.serviceUrl.defaultZone: http://eureka-server1:8500/eureka/
      eureka.client.fetchRegistry: "true"
      eureka.client.register-with-eureka: "true"


  db:
    image: mysql:5.7.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: welcome2019
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo2019
    networks:
      - db-net
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  
    volumes:
      - ./demo/dbdata/mariadb:/var/lib/mysql

networks:
  eureka-net:
    driver: bridge
  db-net:
    driver: bridge
    