package com.eccl.cloud.demo.domain;

import javax.persistence.Id;
import javax.persistence.Table;

@Table
public class SysUserPos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_pos.id
     *
     * @mbg.generated
     */
	@Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_pos.pos_id
     *
     * @mbg.generated
     */
    private Long posId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_pos.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_pos.is_primary_pos
     *
     * @mbg.generated
     */
    private String isPrimaryPos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_pos.id
     *
     * @return the value of sys_user_pos.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_pos.id
     *
     * @param id the value for sys_user_pos.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_pos.pos_id
     *
     * @return the value of sys_user_pos.pos_id
     *
     * @mbg.generated
     */
    public Long getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_pos.pos_id
     *
     * @param posId the value for sys_user_pos.pos_id
     *
     * @mbg.generated
     */
    public void setPosId(Long posId) {
        this.posId = posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_pos.user_id
     *
     * @return the value of sys_user_pos.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_pos.user_id
     *
     * @param userId the value for sys_user_pos.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_pos.is_primary_pos
     *
     * @return the value of sys_user_pos.is_primary_pos
     *
     * @mbg.generated
     */
    public String getIsPrimaryPos() {
        return isPrimaryPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_pos.is_primary_pos
     *
     * @param isPrimaryPos the value for sys_user_pos.is_primary_pos
     *
     * @mbg.generated
     */
    public void setIsPrimaryPos(String isPrimaryPos) {
        this.isPrimaryPos = isPrimaryPos;
    }
}