package com.eccl.cloud.common.domain;

import java.io.Serializable;
import java.util.Date;

public class Equipmentdahdtd implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 部件名称
     */
    private String unitname;

    /**
     * 缺陷内容
     */
    private String defectcontent;

    /**
     * 原因
     */
    private String reason;

    /**
     * 处理措施
     */
    private String measure;

    /**
     * 处理时间
     */
    private Date handlingtime;

    /**
     * 本次检修注意事项
     */
    private String pfiam;

    /**
     * 使用寿命
     */
    private String lifelength;

    /**
     * 上次更换时间
     */
    private Date lastchangetime;

    /**
     * 计划下次更换时间
     */
    private Date plannextchange;

    /**
     * 关联设备表ID
     */
    private String equimentid;
    
    private String bid;

    public String getBid() {
		return bid;
	}

	public void setBid(String bid) {
		this.bid = bid;
	}

	/**
     * c54_equipment_dahd_td
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.id
     *
     * @return the value of c54_equipment_dahd_td.id
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.id
     *
     * @param id the value for c54_equipment_dahd_td.id
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.unitname
     *
     * @return the value of c54_equipment_dahd_td.unitname
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.unitname
     *
     * @param unitname the value for c54_equipment_dahd_td.unitname
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname == null ? null : unitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.defectcontent
     *
     * @return the value of c54_equipment_dahd_td.defectcontent
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getDefectcontent() {
        return defectcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.defectcontent
     *
     * @param defectcontent the value for c54_equipment_dahd_td.defectcontent
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setDefectcontent(String defectcontent) {
        this.defectcontent = defectcontent == null ? null : defectcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.reason
     *
     * @return the value of c54_equipment_dahd_td.reason
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.reason
     *
     * @param reason the value for c54_equipment_dahd_td.reason
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.measure
     *
     * @return the value of c54_equipment_dahd_td.measure
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.measure
     *
     * @param measure the value for c54_equipment_dahd_td.measure
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.handlingtime
     *
     * @return the value of c54_equipment_dahd_td.handlingtime
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public Date getHandlingtime() {
        return handlingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.handlingtime
     *
     * @param handlingtime the value for c54_equipment_dahd_td.handlingtime
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setHandlingtime(Date handlingtime) {
        this.handlingtime = handlingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.pfiam
     *
     * @return the value of c54_equipment_dahd_td.pfiam
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getPfiam() {
        return pfiam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.pfiam
     *
     * @param pfiam the value for c54_equipment_dahd_td.pfiam
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setPfiam(String pfiam) {
        this.pfiam = pfiam == null ? null : pfiam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.lifelength
     *
     * @return the value of c54_equipment_dahd_td.lifelength
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getLifelength() {
        return lifelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.lifelength
     *
     * @param lifelength the value for c54_equipment_dahd_td.lifelength
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setLifelength(String lifelength) {
        this.lifelength = lifelength == null ? null : lifelength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.lastchangetime
     *
     * @return the value of c54_equipment_dahd_td.lastchangetime
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.lastchangetime
     *
     * @param lastchangetime the value for c54_equipment_dahd_td.lastchangetime
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.plannextchange
     *
     * @return the value of c54_equipment_dahd_td.plannextchange
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public Date getPlannextchange() {
        return plannextchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.plannextchange
     *
     * @param plannextchange the value for c54_equipment_dahd_td.plannextchange
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setPlannextchange(Date plannextchange) {
        this.plannextchange = plannextchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_dahd_td.equimentid
     *
     * @return the value of c54_equipment_dahd_td.equimentid
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public String getEquimentid() {
        return equimentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_dahd_td.equimentid
     *
     * @param equimentid the value for c54_equipment_dahd_td.equimentid
     *
     * @mbg.generated Tue Aug 21 14:22:31 CST 2018
     */
    public void setEquimentid(String equimentid) {
        this.equimentid = equimentid;
    }
}