package com.eccl.cloud.common.domain;

import java.io.Serializable;

public class Equipmentparamnametd implements Serializable {
    /**
     * 主键id
     */
    private Long id;

    /**
     * 参数名称
     */
    private String paramname;

    /**
     * 单位
     */
    private String unit;

    /**
     * 技术规范
     */
    private String technicalspecifications;

    /**
     * 备用1
     */
    private String spare1;

    /**
     * 备用2
     */
    private String spare2;

    /**
     * 备用3
     */
    private String spare3;
    
    private String bid;

    public String getBid() {
		return bid;
	}

	public void setBid(String bid) {
		this.bid = bid == null ? null : bid.trim();
	}

	/**
     * c54_equipment_paramname_td
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.id
     *
     * @return the value of c54_equipment_paramname_td.id
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.id
     *
     * @param id the value for c54_equipment_paramname_td.id
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.paramName
     *
     * @return the value of c54_equipment_paramname_td.paramName
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getParamname() {
        return paramname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.paramName
     *
     * @param paramname the value for c54_equipment_paramname_td.paramName
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setParamname(String paramname) {
        this.paramname = paramname == null ? null : paramname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.unit
     *
     * @return the value of c54_equipment_paramname_td.unit
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.unit
     *
     * @param unit the value for c54_equipment_paramname_td.unit
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.technicalSpecifications
     *
     * @return the value of c54_equipment_paramname_td.technicalSpecifications
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getTechnicalspecifications() {
        return technicalspecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.technicalSpecifications
     *
     * @param technicalspecifications the value for c54_equipment_paramname_td.technicalSpecifications
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setTechnicalspecifications(String technicalspecifications) {
        this.technicalspecifications = technicalspecifications == null ? null : technicalspecifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.spare1
     *
     * @return the value of c54_equipment_paramname_td.spare1
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.spare1
     *
     * @param spare1 the value for c54_equipment_paramname_td.spare1
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.spare2
     *
     * @return the value of c54_equipment_paramname_td.spare2
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.spare2
     *
     * @param spare2 the value for c54_equipment_paramname_td.spare2
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_equipment_paramname_td.spare3
     *
     * @return the value of c54_equipment_paramname_td.spare3
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_equipment_paramname_td.spare3
     *
     * @param spare3 the value for c54_equipment_paramname_td.spare3
     *
     * @mbg.generated Wed Sep 19 15:42:57 CST 2018
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3 == null ? null : spare3.trim();
    }
}