package com.eccl.cloud.common.domain;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotBlank;

@Table
public class SysOrg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_id
	 * @mbg.generated
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_name
	 * @mbg.generated
	 */
	@NotBlank
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.parent_id
	 * @mbg.generated
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.show_index
	 * @mbg.generated
	 */
	private Integer showIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_code
	 * @mbg.generated
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_level
	 * @mbg.generated
	 */
	private String orgLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.remark
	 * @mbg.generated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_leader
	 * @mbg.generated
	 */
	private String orgLeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_vice_leader
	 * @mbg.generated
	 */
	private String orgViceLeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.state
	 * @mbg.generated
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_vice_leadername
	 * @mbg.generated
	 */
	private String orgViceLeadername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.org_leadername
	 * @mbg.generated
	 */
	private String orgLeadername;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_id
	 * @return  the value of sys_org.org_id
	 * @mbg.generated
	 */
	public Long getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_id
	 * @param orgId  the value for sys_org.org_id
	 * @mbg.generated
	 */
	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_name
	 * @return  the value of sys_org.org_name
	 * @mbg.generated
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_name
	 * @param orgName  the value for sys_org.org_name
	 * @mbg.generated
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.parent_id
	 * @return  the value of sys_org.parent_id
	 * @mbg.generated
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.parent_id
	 * @param parentId  the value for sys_org.parent_id
	 * @mbg.generated
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.show_index
	 * @return  the value of sys_org.show_index
	 * @mbg.generated
	 */
	public Integer getShowIndex() {
		return showIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.show_index
	 * @param showIndex  the value for sys_org.show_index
	 * @mbg.generated
	 */
	public void setShowIndex(Integer showIndex) {
		this.showIndex = showIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_code
	 * @return  the value of sys_org.org_code
	 * @mbg.generated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_code
	 * @param orgCode  the value for sys_org.org_code
	 * @mbg.generated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_level
	 * @return  the value of sys_org.org_level
	 * @mbg.generated
	 */
	public String getOrgLevel() {
		return orgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_level
	 * @param orgLevel  the value for sys_org.org_level
	 * @mbg.generated
	 */
	public void setOrgLevel(String orgLevel) {
		this.orgLevel = orgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.remark
	 * @return  the value of sys_org.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.remark
	 * @param remark  the value for sys_org.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_leader
	 * @return  the value of sys_org.org_leader
	 * @mbg.generated
	 */
	public String getOrgLeader() {
		return orgLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_leader
	 * @param orgLeader  the value for sys_org.org_leader
	 * @mbg.generated
	 */
	public void setOrgLeader(String orgLeader) {
		this.orgLeader = orgLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_vice_leader
	 * @return  the value of sys_org.org_vice_leader
	 * @mbg.generated
	 */
	public String getOrgViceLeader() {
		return orgViceLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_vice_leader
	 * @param orgViceLeader  the value for sys_org.org_vice_leader
	 * @mbg.generated
	 */
	public void setOrgViceLeader(String orgViceLeader) {
		this.orgViceLeader = orgViceLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.state
	 * @return  the value of sys_org.state
	 * @mbg.generated
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.state
	 * @param state  the value for sys_org.state
	 * @mbg.generated
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_vice_leadername
	 * @return  the value of sys_org.org_vice_leadername
	 * @mbg.generated
	 */
	public String getOrgViceLeadername() {
		return orgViceLeadername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_vice_leadername
	 * @param orgViceLeadername  the value for sys_org.org_vice_leadername
	 * @mbg.generated
	 */
	public void setOrgViceLeadername(String orgViceLeadername) {
		this.orgViceLeadername = orgViceLeadername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.org_leadername
	 * @return  the value of sys_org.org_leadername
	 * @mbg.generated
	 */
	public String getOrgLeadername() {
		return orgLeadername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.org_leadername
	 * @param orgLeadername  the value for sys_org.org_leadername
	 * @mbg.generated
	 */
	public void setOrgLeadername(String orgLeadername) {
		this.orgLeadername = orgLeadername;
	}

	@Transient
	private String orgNameEqual;

	public String getOrgNameEqual() {
		return orgNameEqual;
	}

	public void setOrgNameEqual(String orgNameEqual) {
		this.orgNameEqual = orgNameEqual;
	}
	
	
}