package com.eccl.cloud.common.domain;
import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;

@Table
public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_id
	 * @mbg.generated
	 */
	@Id
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_code
	 * @mbg.generated
	 */
	@NotBlank
	private String userCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_name
	 * @mbg.generated
	 */
	@NotBlank
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbg.generated
	 */
	@NotBlank
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.org_id
	 * @mbg.generated
	 */
	private Long orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.org_name
	 * @mbg.generated
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.company_id
	 * @mbg.generated
	 */
	private Long companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.org_path
	 * @mbg.generated
	 */
	private String orgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.login_state
	 * @mbg.generated
	 */
	private String loginState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.account_state
	 * @mbg.generated
	 */
	private String accountState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.leader_id
	 * @mbg.generated
	 */
	private Long leaderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.leader_name
	 * @mbg.generated
	 */
	private String leaderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.cell_phone
	 * @mbg.generated
	 */
	private String cellPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.lock_time_start
	 * @mbg.generated
	 */
	private Date lockTimeStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.lock_time_end
	 * @mbg.generated
	 */
	private Date lockTimeEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.sex
	 * @mbg.generated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.birthday
	 * @mbg.generated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.show_index
	 * @mbg.generated
	 */
	private Integer showIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.photo
	 * @mbg.generated
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id_number
	 * @mbg.generated
	 */
	private String idNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.face_id
	 * @mbg.generated
	 */
	private String faceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_no
	 * @mbg.generated
	 */
	private String userNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_user
	 * @mbg.generated
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.job
	 * @mbg.generated
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.category
	 * @mbg.generated
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.work_type
	 * @mbg.generated
	 */
	private String workType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.education
	 * @mbg.generated
	 */
	private String education;
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_id
	 * @return  the value of sys_user.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_id
	 * @param userId  the value for sys_user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_code
	 * @return  the value of sys_user.user_code
	 * @mbg.generated
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_code
	 * @param userCode  the value for sys_user.user_code
	 * @mbg.generated
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_name
	 * @return  the value of sys_user.user_name
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_name
	 * @param userName  the value for sys_user.user_name
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 * @return  the value of sys_user.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 * @param createTime  the value for sys_user.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.org_id
	 * @return  the value of sys_user.org_id
	 * @mbg.generated
	 */
	public Long getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.org_id
	 * @param orgId  the value for sys_user.org_id
	 * @mbg.generated
	 */
	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.org_name
	 * @return  the value of sys_user.org_name
	 * @mbg.generated
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.org_name
	 * @param orgName  the value for sys_user.org_name
	 * @mbg.generated
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.company_id
	 * @return  the value of sys_user.company_id
	 * @mbg.generated
	 */
	public Long getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.company_id
	 * @param companyId  the value for sys_user.company_id
	 * @mbg.generated
	 */
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.org_path
	 * @return  the value of sys_user.org_path
	 * @mbg.generated
	 */
	public String getOrgPath() {
		return orgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.org_path
	 * @param orgPath  the value for sys_user.org_path
	 * @mbg.generated
	 */
	public void setOrgPath(String orgPath) {
		this.orgPath = orgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.login_state
	 * @return  the value of sys_user.login_state
	 * @mbg.generated
	 */
	public String getLoginState() {
		return loginState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.login_state
	 * @param loginState  the value for sys_user.login_state
	 * @mbg.generated
	 */
	public void setLoginState(String loginState) {
		this.loginState = loginState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.account_state
	 * @return  the value of sys_user.account_state
	 * @mbg.generated
	 */
	public String getAccountState() {
		return accountState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.account_state
	 * @param accountState  the value for sys_user.account_state
	 * @mbg.generated
	 */
	public void setAccountState(String accountState) {
		this.accountState = accountState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.leader_id
	 * @return  the value of sys_user.leader_id
	 * @mbg.generated
	 */
	public Long getLeaderId() {
		return leaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.leader_id
	 * @param leaderId  the value for sys_user.leader_id
	 * @mbg.generated
	 */
	public void setLeaderId(Long leaderId) {
		this.leaderId = leaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.leader_name
	 * @return  the value of sys_user.leader_name
	 * @mbg.generated
	 */
	public String getLeaderName() {
		return leaderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.leader_name
	 * @param leaderName  the value for sys_user.leader_name
	 * @mbg.generated
	 */
	public void setLeaderName(String leaderName) {
		this.leaderName = leaderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.phone
	 * @return  the value of sys_user.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.phone
	 * @param phone  the value for sys_user.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.cell_phone
	 * @return  the value of sys_user.cell_phone
	 * @mbg.generated
	 */
	public String getCellPhone() {
		return cellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.cell_phone
	 * @param cellPhone  the value for sys_user.cell_phone
	 * @mbg.generated
	 */
	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.lock_time_start
	 * @return  the value of sys_user.lock_time_start
	 * @mbg.generated
	 */
	public Date getLockTimeStart() {
		return lockTimeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.lock_time_start
	 * @param lockTimeStart  the value for sys_user.lock_time_start
	 * @mbg.generated
	 */
	public void setLockTimeStart(Date lockTimeStart) {
		this.lockTimeStart = lockTimeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.lock_time_end
	 * @return  the value of sys_user.lock_time_end
	 * @mbg.generated
	 */
	public Date getLockTimeEnd() {
		return lockTimeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.lock_time_end
	 * @param lockTimeEnd  the value for sys_user.lock_time_end
	 * @mbg.generated
	 */
	public void setLockTimeEnd(Date lockTimeEnd) {
		this.lockTimeEnd = lockTimeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.sex
	 * @return  the value of sys_user.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.sex
	 * @param sex  the value for sys_user.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.birthday
	 * @return  the value of sys_user.birthday
	 * @mbg.generated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.birthday
	 * @param birthday  the value for sys_user.birthday
	 * @mbg.generated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.show_index
	 * @return  the value of sys_user.show_index
	 * @mbg.generated
	 */
	public Integer getShowIndex() {
		return showIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.show_index
	 * @param showIndex  the value for sys_user.show_index
	 * @mbg.generated
	 */
	public void setShowIndex(Integer showIndex) {
		this.showIndex = showIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.photo
	 * @return  the value of sys_user.photo
	 * @mbg.generated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.photo
	 * @param photo  the value for sys_user.photo
	 * @mbg.generated
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id_number
	 * @return  the value of sys_user.id_number
	 * @mbg.generated
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id_number
	 * @param idNumber  the value for sys_user.id_number
	 * @mbg.generated
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.face_id
	 * @return  the value of sys_user.face_id
	 * @mbg.generated
	 */
	public String getFaceId() {
		return faceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.face_id
	 * @param faceId  the value for sys_user.face_id
	 * @mbg.generated
	 */
	public void setFaceId(String faceId) {
		this.faceId = faceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_no
	 * @return  the value of sys_user.user_no
	 * @mbg.generated
	 */
	public String getUserNo() {
		return userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_no
	 * @param userNo  the value for sys_user.user_no
	 * @mbg.generated
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_user
	 * @return  the value of sys_user.create_user
	 * @mbg.generated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_user
	 * @param createUser  the value for sys_user.create_user
	 * @mbg.generated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.job
	 * @return  the value of sys_user.job
	 * @mbg.generated
	 */
	public String getJob() {
		return job;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.jobName
	 * @mbg.generated
	 */
	private String jobname;
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.job
	 * @param job  the value for sys_user.job
	 * @mbg.generated
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.category
	 * @return  the value of sys_user.category
	 * @mbg.generated
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.category
	 * @param category  the value for sys_user.category
	 * @mbg.generated
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.work_type
	 * @return  the value of sys_user.work_type
	 * @mbg.generated
	 */
	public String getWorkType() {
		return workType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.work_type
	 * @param workType  the value for sys_user.work_type
	 * @mbg.generated
	 */
	public void setWorkType(String workType) {
		this.workType = workType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.education
	 * @return  the value of sys_user.education
	 * @mbg.generated
	 */
	public String getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.education
	 * @param education  the value for sys_user.education
	 * @mbg.generated
	 */
	public void setEducation(String education) {
		this.education = education;
	}
	
	private Long teamId;
	
	private String teamName;
	
	private Long deptId;
	
	private String deptName;
	
	private String companyName;
	
	public String getTeamName() {
		return teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Long getTeamId() {
		return teamId;
	}

	public void setTeamId(Long teamId) {
		this.teamId = teamId;
	}

	public Long getDeptId() {
		return deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	
	private String issignin;
	
	private String isfacerecognition;
	
	private Date disclosedate;


	public String getIssignin() {
		return issignin;
	}

	public void setIssignin(String issignin) {
		this.issignin = issignin;
	}

	public String getIsfacerecognition() {
		return isfacerecognition;
	}

	public void setIsfacerecognition(String isfacerecognition) {
		this.isfacerecognition = isfacerecognition;
	}

	public Date getDisclosedate() {
		return disclosedate;
	}

	public void setDisclosedate(Date disclosedate) {
		this.disclosedate = disclosedate;
	}

	public String getJobname() {
		return jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}
	
}