package com.eccl.cloud.common.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

@Table
public class TkMainTaskinfoTd implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.id
     *
     * @mbg.generated
     */
	@Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.bid
     *
     * @mbg.generated
     */
 
    private String bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.taskname
     *
     * @mbg.generated
     */
    private String taskname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.categoryid
     *
     * @mbg.generated
     */
    private String categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.categoryname
     *
     * @mbg.generated
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_typeid
     *
     * @mbg.generated
     */
    private String taskTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_typename
     *
     * @mbg.generated
     */
    private String taskTypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.responsibilityid
     *
     * @mbg.generated
     */
    private Integer responsibilityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.responsibilityname
     *
     * @mbg.generated
     */
    private String responsibilityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_status
     *
     * @mbg.generated
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.Levelofrisk
     *
     * @mbg.generated
     */
    private String levelofrisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.begintime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(timezone="GMT+8",pattern="yyyy-MM-dd")
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.endtime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(timezone="GMT+8",pattern="yyyy-MM-dd")
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_code
     *
     * @mbg.generated
     */
    private String taskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.plan_begintime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(timezone="GMT+8",pattern="yyyy-MM-dd")
    private Date planBegintime;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.plan_endtime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(timezone="GMT+8",pattern="yyyy-MM-dd")
    private Date planEndtime;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.complete
     *
     * @mbg.generated
     */
    private String complete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.history_flag
     *
     * @mbg.generated
     */
    private String historyFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.workgroupid
     *
     * @mbg.generated
     */
    private Integer workgroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.workgroup
     *
     * @mbg.generated
     */
    private String workgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_order
     *
     * @mbg.generated
     */
    private Integer taskOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_weight
     *
     * @mbg.generated
     */
    private String taskWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.actinstanceid
     *
     * @mbg.generated
     */
    private String actinstanceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.actdefineid
     *
     * @mbg.generated
     */
    private String actdefineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.acttaskid
     *
     * @mbg.generated
     */
    private String acttaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.typicalbid
     *
     * @mbg.generated
     */
    private String typicalbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.typicaltype
     *
     * @mbg.generated
     */
    private String typicaltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.createperson
     *
     * @mbg.generated
     */
    private String createperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_main_taskinfo_td.task_remark
     *
     * @mbg.generated
     */
    private String taskRemark;
    
    private String taskmembers;
    
    private String taskmembersid;
    
    @Transient
    private String areaid;
    
    public String getTaskmembersid() {
		return taskmembersid;
	}

	public void setTaskmembersid(String taskmembersid) {
		this.taskmembersid = taskmembersid;
	}

	private Long createpersonid;

	public Long getCreatepersonid() {
		return createpersonid;
	}

	public void setCreatepersonid(Long createpersonid) {
		this.createpersonid = createpersonid;
	}

	public String getTaskmembers() {
		return taskmembers;
	}

	public void setTaskmembers(String taskmembers) {
		this.taskmembers = taskmembers;
	}

	private String overhaullevel;

    public String getOverhaullevel() {
		return overhaullevel;
	}

	public void setOverhaullevel(String overhaullevel) {
		this.overhaullevel = overhaullevel;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_main_taskinfo_td
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.id
     *
     * @return the value of tk_main_taskinfo_td.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.id
     *
     * @param id the value for tk_main_taskinfo_td.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.bid
     *
     * @return the value of tk_main_taskinfo_td.bid
     *
     * @mbg.generated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.bid
     *
     * @param bid the value for tk_main_taskinfo_td.bid
     *
     * @mbg.generated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.taskname
     *
     * @return the value of tk_main_taskinfo_td.taskname
     *
     * @mbg.generated
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.taskname
     *
     * @param taskname the value for tk_main_taskinfo_td.taskname
     *
     * @mbg.generated
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.pid
     *
     * @return the value of tk_main_taskinfo_td.pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.pid
     *
     * @param pid the value for tk_main_taskinfo_td.pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.categoryid
     *
     * @return the value of tk_main_taskinfo_td.categoryid
     *
     * @mbg.generated
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.categoryid
     *
     * @param categoryid the value for tk_main_taskinfo_td.categoryid
     *
     * @mbg.generated
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.categoryname
     *
     * @return the value of tk_main_taskinfo_td.categoryname
     *
     * @mbg.generated
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.categoryname
     *
     * @param categoryname the value for tk_main_taskinfo_td.categoryname
     *
     * @mbg.generated
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_typeid
     *
     * @return the value of tk_main_taskinfo_td.task_typeid
     *
     * @mbg.generated
     */
    public String getTaskTypeid() {
        return taskTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_typeid
     *
     * @param taskTypeid the value for tk_main_taskinfo_td.task_typeid
     *
     * @mbg.generated
     */
    public void setTaskTypeid(String taskTypeid) {
        this.taskTypeid = taskTypeid == null ? null : taskTypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_typename
     *
     * @return the value of tk_main_taskinfo_td.task_typename
     *
     * @mbg.generated
     */
    public String getTaskTypename() {
        return taskTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_typename
     *
     * @param taskTypename the value for tk_main_taskinfo_td.task_typename
     *
     * @mbg.generated
     */
    public void setTaskTypename(String taskTypename) {
        this.taskTypename = taskTypename == null ? null : taskTypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.responsibilityid
     *
     * @return the value of tk_main_taskinfo_td.responsibilityid
     *
     * @mbg.generated
     */
    public Integer getResponsibilityid() {
        return responsibilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.responsibilityid
     *
     * @param responsibilityid the value for tk_main_taskinfo_td.responsibilityid
     *
     * @mbg.generated
     */
    public void setResponsibilityid(Integer responsibilityid) {
        this.responsibilityid = responsibilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.responsibilityname
     *
     * @return the value of tk_main_taskinfo_td.responsibilityname
     *
     * @mbg.generated
     */
    public String getResponsibilityname() {
        return responsibilityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.responsibilityname
     *
     * @param responsibilityname the value for tk_main_taskinfo_td.responsibilityname
     *
     * @mbg.generated
     */
    public void setResponsibilityname(String responsibilityname) {
        this.responsibilityname = responsibilityname == null ? null : responsibilityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_status
     *
     * @return the value of tk_main_taskinfo_td.task_status
     *
     * @mbg.generated
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_status
     *
     * @param taskStatus the value for tk_main_taskinfo_td.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.Levelofrisk
     *
     * @return the value of tk_main_taskinfo_td.Levelofrisk
     *
     * @mbg.generated
     */
    public String getLevelofrisk() {
        return levelofrisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.Levelofrisk
     *
     * @param levelofrisk the value for tk_main_taskinfo_td.Levelofrisk
     *
     * @mbg.generated
     */
    public void setLevelofrisk(String levelofrisk) {
        this.levelofrisk = levelofrisk == null ? null : levelofrisk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.begintime
     *
     * @return the value of tk_main_taskinfo_td.begintime
     *
     * @mbg.generated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.begintime
     *
     * @param begintime the value for tk_main_taskinfo_td.begintime
     *
     * @mbg.generated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.endtime
     *
     * @return the value of tk_main_taskinfo_td.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.endtime
     *
     * @param endtime the value for tk_main_taskinfo_td.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_code
     *
     * @return the value of tk_main_taskinfo_td.task_code
     *
     * @mbg.generated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_code
     *
     * @param taskCode the value for tk_main_taskinfo_td.task_code
     *
     * @mbg.generated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.plan_begintime
     *
     * @return the value of tk_main_taskinfo_td.plan_begintime
     *
     * @mbg.generated
     */
    
    public Date getPlanBegintime() {
        return planBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.plan_begintime
     *
     * @param planBegintime the value for tk_main_taskinfo_td.plan_begintime
     *
     * @mbg.generated
     */
    public void setPlanBegintime(Date planBegintime) {
        this.planBegintime = planBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.plan_endtime
     *
     * @return the value of tk_main_taskinfo_td.plan_endtime
     *
     * @mbg.generated
     */
    public Date getPlanEndtime() {
        return planEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.plan_endtime
     *
     * @param planEndtime the value for tk_main_taskinfo_td.plan_endtime
     *
     * @mbg.generated
     */
    public void setPlanEndtime(Date planEndtime) {
        this.planEndtime = planEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.complete
     *
     * @return the value of tk_main_taskinfo_td.complete
     *
     * @mbg.generated
     */
    public String getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.complete
     *
     * @param complete the value for tk_main_taskinfo_td.complete
     *
     * @mbg.generated
     */
    public void setComplete(String complete) {
        this.complete = complete == null ? null : complete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.history_flag
     *
     * @return the value of tk_main_taskinfo_td.history_flag
     *
     * @mbg.generated
     */
    public String getHistoryFlag() {
        return historyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.history_flag
     *
     * @param historyFlag the value for tk_main_taskinfo_td.history_flag
     *
     * @mbg.generated
     */
    public void setHistoryFlag(String historyFlag) {
        this.historyFlag = historyFlag == null ? null : historyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.workgroupid
     *
     * @return the value of tk_main_taskinfo_td.workgroupid
     *
     * @mbg.generated
     */
    public Integer getWorkgroupid() {
        return workgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.workgroupid
     *
     * @param workgroupid the value for tk_main_taskinfo_td.workgroupid
     *
     * @mbg.generated
     */
    public void setWorkgroupid(Integer workgroupid) {
        this.workgroupid = workgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.workgroup
     *
     * @return the value of tk_main_taskinfo_td.workgroup
     *
     * @mbg.generated
     */
    public String getWorkgroup() {
        return workgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.workgroup
     *
     * @param workgroup the value for tk_main_taskinfo_td.workgroup
     *
     * @mbg.generated
     */
    public void setWorkgroup(String workgroup) {
        this.workgroup = workgroup == null ? null : workgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_order
     *
     * @return the value of tk_main_taskinfo_td.task_order
     *
     * @mbg.generated
     */
    public Integer getTaskOrder() {
        return taskOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_order
     *
     * @param taskOrder the value for tk_main_taskinfo_td.task_order
     *
     * @mbg.generated
     */
    public void setTaskOrder(Integer taskOrder) {
        this.taskOrder = taskOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_weight
     *
     * @return the value of tk_main_taskinfo_td.task_weight
     *
     * @mbg.generated
     */
    public String getTaskWeight() {
        return taskWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_weight
     *
     * @param taskWeight the value for tk_main_taskinfo_td.task_weight
     *
     * @mbg.generated
     */
    public void setTaskWeight(String taskWeight) {
        this.taskWeight = taskWeight == null ? null : taskWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.actinstanceid
     *
     * @return the value of tk_main_taskinfo_td.actinstanceid
     *
     * @mbg.generated
     */
    public String getActinstanceid() {
        return actinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.actinstanceid
     *
     * @param actinstanceid the value for tk_main_taskinfo_td.actinstanceid
     *
     * @mbg.generated
     */
    public void setActinstanceid(String actinstanceid) {
        this.actinstanceid = actinstanceid == null ? null : actinstanceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.actdefineid
     *
     * @return the value of tk_main_taskinfo_td.actdefineid
     *
     * @mbg.generated
     */
    public String getActdefineid() {
        return actdefineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.actdefineid
     *
     * @param actdefineid the value for tk_main_taskinfo_td.actdefineid
     *
     * @mbg.generated
     */
    public void setActdefineid(String actdefineid) {
        this.actdefineid = actdefineid == null ? null : actdefineid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.acttaskid
     *
     * @return the value of tk_main_taskinfo_td.acttaskid
     *
     * @mbg.generated
     */
    public String getActtaskid() {
        return acttaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.acttaskid
     *
     * @param acttaskid the value for tk_main_taskinfo_td.acttaskid
     *
     * @mbg.generated
     */
    public void setActtaskid(String acttaskid) {
        this.acttaskid = acttaskid == null ? null : acttaskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.typicalbid
     *
     * @return the value of tk_main_taskinfo_td.typicalbid
     *
     * @mbg.generated
     */
    public String getTypicalbid() {
        return typicalbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.typicalbid
     *
     * @param typicalbid the value for tk_main_taskinfo_td.typicalbid
     *
     * @mbg.generated
     */
    public void setTypicalbid(String typicalbid) {
        this.typicalbid = typicalbid == null ? null : typicalbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.typicaltype
     *
     * @return the value of tk_main_taskinfo_td.typicaltype
     *
     * @mbg.generated
     */
    public String getTypicaltype() {
        return typicaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.typicaltype
     *
     * @param typicaltype the value for tk_main_taskinfo_td.typicaltype
     *
     * @mbg.generated
     */
    public void setTypicaltype(String typicaltype) {
        this.typicaltype = typicaltype == null ? null : typicaltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.createperson
     *
     * @return the value of tk_main_taskinfo_td.createperson
     *
     * @mbg.generated
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.createperson
     *
     * @param createperson the value for tk_main_taskinfo_td.createperson
     *
     * @mbg.generated
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson == null ? null : createperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.parent
     *
     * @return the value of tk_main_taskinfo_td.parent
     *
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.parent
     *
     * @param parent the value for tk_main_taskinfo_td.parent
     *
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_main_taskinfo_td.task_remark
     *
     * @return the value of tk_main_taskinfo_td.task_remark
     *
     * @mbg.generated
     */
    public String getTaskRemark() {
        return taskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_main_taskinfo_td.task_remark
     *
     * @param taskRemark the value for tk_main_taskinfo_td.task_remark
     *
     * @mbg.generated
     */
    public void setTaskRemark(String taskRemark) {
        this.taskRemark = taskRemark == null ? null : taskRemark.trim();
    }
    
    private String flowstate;

	public String getFlowstate() {
		return flowstate;
	}

	public void setFlowstate(String flowstate) {
		this.flowstate = flowstate;
	}

	public String getAreaid() {
		return areaid;
	}

	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}
    
}