package com.eccl.cloud.common.domain;

import java.util.Date;

public class Tooltd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolnum
     *
     * @mbg.generated
     */
    private String toolnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolname
     *
     * @mbg.generated
     */
    private String toolname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.tooldept
     *
     * @mbg.generated
     */
    private String tooldept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.tooldeptid
     *
     * @mbg.generated
     */
    private String tooldeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolteam
     *
     * @mbg.generated
     */
    private String toolteam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolteamid
     *
     * @mbg.generated
     */
    private String toolteamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolhead
     *
     * @mbg.generated
     */
    private String toolhead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolheadid
     *
     * @mbg.generated
     */
    private String toolheadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.tooltype
     *
     * @mbg.generated
     */
    private String tooltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.tooltypeid
     *
     * @mbg.generated
     */
    private String tooltypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolcheckstatus
     *
     * @mbg.generated
     */
    private String toolcheckstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolisuse
     *
     * @mbg.generated
     */
    private String toolisuse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolremark
     *
     * @mbg.generated
     */
    private String toolremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolfilename
     *
     * @mbg.generated
     */
    private String toolfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolfilepath
     *
     * @mbg.generated
     */
    private String toolfilepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.createperson
     *
     * @mbg.generated
     */
    private String createperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.createpersonid
     *
     * @mbg.generated
     */
    private String createpersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.operatetime
     *
     * @mbg.generated
     */
    private Date operatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.operateperson
     *
     * @mbg.generated
     */
    private String operateperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.operatepersonid
     *
     * @mbg.generated
     */
    private String operatepersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.spare0
     *
     * @mbg.generated
     */
    private String spare0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.spare1
     *
     * @mbg.generated
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.spare2
     *
     * @mbg.generated
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.spare3
     *
     * @mbg.generated
     */
    private String spare3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.spare4
     *
     * @mbg.generated
     */
    private String spare4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.bid
     *
     * @mbg.generated
     */
    private String bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolparam
     *
     * @mbg.generated
     */
    private String toolparam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c54_tool_td.toolstandard
     *
     * @mbg.generated
     */
    private String toolstandard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.id
     *
     * @return the value of c54_tool_td.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.id
     *
     * @param id the value for c54_tool_td.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolnum
     *
     * @return the value of c54_tool_td.toolnum
     *
     * @mbg.generated
     */
    public String getToolnum() {
        return toolnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolnum
     *
     * @param toolnum the value for c54_tool_td.toolnum
     *
     * @mbg.generated
     */
    public void setToolnum(String toolnum) {
        this.toolnum = toolnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolname
     *
     * @return the value of c54_tool_td.toolname
     *
     * @mbg.generated
     */
    public String getToolname() {
        return toolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolname
     *
     * @param toolname the value for c54_tool_td.toolname
     *
     * @mbg.generated
     */
    public void setToolname(String toolname) {
        this.toolname = toolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.tooldept
     *
     * @return the value of c54_tool_td.tooldept
     *
     * @mbg.generated
     */
    public String getTooldept() {
        return tooldept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.tooldept
     *
     * @param tooldept the value for c54_tool_td.tooldept
     *
     * @mbg.generated
     */
    public void setTooldept(String tooldept) {
        this.tooldept = tooldept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.tooldeptid
     *
     * @return the value of c54_tool_td.tooldeptid
     *
     * @mbg.generated
     */
    public String getTooldeptid() {
        return tooldeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.tooldeptid
     *
     * @param tooldeptid the value for c54_tool_td.tooldeptid
     *
     * @mbg.generated
     */
    public void setTooldeptid(String tooldeptid) {
        this.tooldeptid = tooldeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolteam
     *
     * @return the value of c54_tool_td.toolteam
     *
     * @mbg.generated
     */
    public String getToolteam() {
        return toolteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolteam
     *
     * @param toolteam the value for c54_tool_td.toolteam
     *
     * @mbg.generated
     */
    public void setToolteam(String toolteam) {
        this.toolteam = toolteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolteamid
     *
     * @return the value of c54_tool_td.toolteamid
     *
     * @mbg.generated
     */
    public String getToolteamid() {
        return toolteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolteamid
     *
     * @param toolteamid the value for c54_tool_td.toolteamid
     *
     * @mbg.generated
     */
    public void setToolteamid(String toolteamid) {
        this.toolteamid = toolteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolhead
     *
     * @return the value of c54_tool_td.toolhead
     *
     * @mbg.generated
     */
    public String getToolhead() {
        return toolhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolhead
     *
     * @param toolhead the value for c54_tool_td.toolhead
     *
     * @mbg.generated
     */
    public void setToolhead(String toolhead) {
        this.toolhead = toolhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolheadid
     *
     * @return the value of c54_tool_td.toolheadid
     *
     * @mbg.generated
     */
    public String getToolheadid() {
        return toolheadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolheadid
     *
     * @param toolheadid the value for c54_tool_td.toolheadid
     *
     * @mbg.generated
     */
    public void setToolheadid(String toolheadid) {
        this.toolheadid = toolheadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.tooltype
     *
     * @return the value of c54_tool_td.tooltype
     *
     * @mbg.generated
     */
    public String getTooltype() {
        return tooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.tooltype
     *
     * @param tooltype the value for c54_tool_td.tooltype
     *
     * @mbg.generated
     */
    public void setTooltype(String tooltype) {
        this.tooltype = tooltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.tooltypeid
     *
     * @return the value of c54_tool_td.tooltypeid
     *
     * @mbg.generated
     */
    public String getTooltypeid() {
        return tooltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.tooltypeid
     *
     * @param tooltypeid the value for c54_tool_td.tooltypeid
     *
     * @mbg.generated
     */
    public void setTooltypeid(String tooltypeid) {
        this.tooltypeid = tooltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolcheckstatus
     *
     * @return the value of c54_tool_td.toolcheckstatus
     *
     * @mbg.generated
     */
    public String getToolcheckstatus() {
        return toolcheckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolcheckstatus
     *
     * @param toolcheckstatus the value for c54_tool_td.toolcheckstatus
     *
     * @mbg.generated
     */
    public void setToolcheckstatus(String toolcheckstatus) {
        this.toolcheckstatus = toolcheckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolisuse
     *
     * @return the value of c54_tool_td.toolisuse
     *
     * @mbg.generated
     */
    public String getToolisuse() {
        return toolisuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolisuse
     *
     * @param toolisuse the value for c54_tool_td.toolisuse
     *
     * @mbg.generated
     */
    public void setToolisuse(String toolisuse) {
        this.toolisuse = toolisuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolremark
     *
     * @return the value of c54_tool_td.toolremark
     *
     * @mbg.generated
     */
    public String getToolremark() {
        return toolremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolremark
     *
     * @param toolremark the value for c54_tool_td.toolremark
     *
     * @mbg.generated
     */
    public void setToolremark(String toolremark) {
        this.toolremark = toolremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolfilename
     *
     * @return the value of c54_tool_td.toolfilename
     *
     * @mbg.generated
     */
    public String getToolfilename() {
        return toolfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolfilename
     *
     * @param toolfilename the value for c54_tool_td.toolfilename
     *
     * @mbg.generated
     */
    public void setToolfilename(String toolfilename) {
        this.toolfilename = toolfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolfilepath
     *
     * @return the value of c54_tool_td.toolfilepath
     *
     * @mbg.generated
     */
    public String getToolfilepath() {
        return toolfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolfilepath
     *
     * @param toolfilepath the value for c54_tool_td.toolfilepath
     *
     * @mbg.generated
     */
    public void setToolfilepath(String toolfilepath) {
        this.toolfilepath = toolfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.createtime
     *
     * @return the value of c54_tool_td.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.createtime
     *
     * @param createtime the value for c54_tool_td.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.createperson
     *
     * @return the value of c54_tool_td.createperson
     *
     * @mbg.generated
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.createperson
     *
     * @param createperson the value for c54_tool_td.createperson
     *
     * @mbg.generated
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.createpersonid
     *
     * @return the value of c54_tool_td.createpersonid
     *
     * @mbg.generated
     */
    public String getCreatepersonid() {
        return createpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.createpersonid
     *
     * @param createpersonid the value for c54_tool_td.createpersonid
     *
     * @mbg.generated
     */
    public void setCreatepersonid(String createpersonid) {
        this.createpersonid = createpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.operatetime
     *
     * @return the value of c54_tool_td.operatetime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.operatetime
     *
     * @param operatetime the value for c54_tool_td.operatetime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.operateperson
     *
     * @return the value of c54_tool_td.operateperson
     *
     * @mbg.generated
     */
    public String getOperateperson() {
        return operateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.operateperson
     *
     * @param operateperson the value for c54_tool_td.operateperson
     *
     * @mbg.generated
     */
    public void setOperateperson(String operateperson) {
        this.operateperson = operateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.operatepersonid
     *
     * @return the value of c54_tool_td.operatepersonid
     *
     * @mbg.generated
     */
    public String getOperatepersonid() {
        return operatepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.operatepersonid
     *
     * @param operatepersonid the value for c54_tool_td.operatepersonid
     *
     * @mbg.generated
     */
    public void setOperatepersonid(String operatepersonid) {
        this.operatepersonid = operatepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.spare0
     *
     * @return the value of c54_tool_td.spare0
     *
     * @mbg.generated
     */
    public String getSpare0() {
        return spare0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.spare0
     *
     * @param spare0 the value for c54_tool_td.spare0
     *
     * @mbg.generated
     */
    public void setSpare0(String spare0) {
        this.spare0 = spare0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.spare1
     *
     * @return the value of c54_tool_td.spare1
     *
     * @mbg.generated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.spare1
     *
     * @param spare1 the value for c54_tool_td.spare1
     *
     * @mbg.generated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.spare2
     *
     * @return the value of c54_tool_td.spare2
     *
     * @mbg.generated
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.spare2
     *
     * @param spare2 the value for c54_tool_td.spare2
     *
     * @mbg.generated
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.spare3
     *
     * @return the value of c54_tool_td.spare3
     *
     * @mbg.generated
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.spare3
     *
     * @param spare3 the value for c54_tool_td.spare3
     *
     * @mbg.generated
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.spare4
     *
     * @return the value of c54_tool_td.spare4
     *
     * @mbg.generated
     */
    public String getSpare4() {
        return spare4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.spare4
     *
     * @param spare4 the value for c54_tool_td.spare4
     *
     * @mbg.generated
     */
    public void setSpare4(String spare4) {
        this.spare4 = spare4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.bid
     *
     * @return the value of c54_tool_td.bid
     *
     * @mbg.generated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.bid
     *
     * @param bid the value for c54_tool_td.bid
     *
     * @mbg.generated
     */
    public void setBid(String bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolparam
     *
     * @return the value of c54_tool_td.toolparam
     *
     * @mbg.generated
     */
    public String getToolparam() {
        return toolparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolparam
     *
     * @param toolparam the value for c54_tool_td.toolparam
     *
     * @mbg.generated
     */
    public void setToolparam(String toolparam) {
        this.toolparam = toolparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c54_tool_td.toolstandard
     *
     * @return the value of c54_tool_td.toolstandard
     *
     * @mbg.generated
     */
    public String getToolstandard() {
        return toolstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c54_tool_td.toolstandard
     *
     * @param toolstandard the value for c54_tool_td.toolstandard
     *
     * @mbg.generated
     */
    public void setToolstandard(String toolstandard) {
        this.toolstandard = toolstandard;
    }
    
    private String state;
    
    private Date disclosedate;

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getDisclosedate() {
		return disclosedate;
	}

	public void setDisclosedate(Date disclosedate) {
		this.disclosedate = disclosedate;
	}
    
}